const response = {
  coursesTaken: [
    {
      school: 'SJSU',
      prerequisites: ['5ea1264cc0b5e9e8c4d34b85', '5ea12656c0b5e9e8c4d34bb1'],
      corequisites: [],
      type: [1],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34b89',
      code: '102',
      area: 'majorRequirement',
      title: ' ',
      department: 'CMPE',
      __v: 0,
      credit: '3.0',
    },
    {
      school: 'SJSU',
      prerequisites: [],
      corequisites: [],
      type: [2],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34bab',
      code: '174',
      area: 'elective',
      title: ' ',
      department: 'CS',
      __v: 0,
    },
    {
      school: 'SJSU',
      prerequisites: ['5ea1264bc0b5e9e8c4d34ae7', '5ea1264cc0b5e9e8c4d34b7d'],
      corequisites: [],
      type: [1],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34b80',
      code: '42',
      area: 'majorRequirement',
      title: ' ',
      department: 'MATH',
      __v: 0,
      credit: '3.0',
    },
    {
      school: 'SJSU',
      prerequisites: [],
      corequisites: [],
      type: [],
      difficulty: 0,
      impaction: 0,
      _id: '5ea12665c0b5e9e8c4d34bb5',
      code: '42W',
      department: 'MATH',
      __v: 0,
    },
    {
      school: 'SJSU',
      prerequisites: [],
      corequisites: [],
      type: [0],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264bc0b5e9e8c4d34ab6',
      code: '57',
      area: 'A3',
      title: ' ',
      department: 'PHIL',
      __v: 0,
    },
    {
      school: 'SJSU',
      prerequisites: ['5ea1264cc0b5e9e8c4d34b85', '5ea12656c0b5e9e8c4d34bb1'],
      corequisites: [],
      type: [1],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34b88',
      code: '120',
      area: 'majorRequirement',
      title: ' ',
      department: 'CMPE',
      __v: 0,
      credit: '3.0',
    },
    {
      school: 'SJSU',
      prerequisites: ['5ea1264cc0b5e9e8c4d34b85'],
      corequisites: [],
      type: [1],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34b84',
      code: '131',
      area: 'majorRequirement',
      title: ' ',
      department: 'CMPE',
      __v: 0,
      credit: '3.0',
    },
    {
      school: 'SJSU',
      prerequisites: ['5ea1264ac0b5e9e8c4d34aac'],
      corequisites: [],
      type: [0, 1],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34b6e',
      code: '10',
      area: 'E1',
      title: ' ',
      department: 'ENGR',
      __v: 1,
      credit: '3.0',
    },
    {
      school: 'SJSU',
      prerequisites: [],
      corequisites: [],
      type: [],
      difficulty: 0,
      impaction: 0,
      _id: '5ea12656c0b5e9e8c4d34bb3',
      code: '100W',
      title: ' ',
      department: 'ENGR',
      __v: 0,
    },
    {
      school: 'SJSU',
      prerequisites: [],
      corequisites: [],
      type: [],
      difficulty: 0,
      impaction: 0,
      _id: '5ea12665c0b5e9e8c4d34bb6',
      code: '15A',
      department: 'HIST',
      __v: 0,
    },
    {
      school: 'SJSU',
      prerequisites: [],
      corequisites: [],
      type: [],
      difficulty: 0,
      impaction: 0,
      _id: '5ea12665c0b5e9e8c4d34bb7',
      code: '35A',
      department: 'KIN',
      __v: 0,
    },
    {
      school: 'SJSU',
      prerequisites: ['5ea1264cc0b5e9e8c4d34b84'],
      corequisites: [],
      type: [1],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34b86',
      code: '133',
      area: 'majorRequirement',
      title: ' ',
      department: 'CMPE',
      __v: 0,
      credit: '3.0',
    },
    {
      school: 'SJSU',
      prerequisites: ['5ea1264cc0b5e9e8c4d34b84'],
      corequisites: [],
      type: [1],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34b8d',
      code: '187',
      area: 'majorRequirement',
      title: ' ',
      department: 'CMPE',
      __v: 0,
      credit: '3.0',
    },
    {
      school: 'SJSU',
      prerequisites: [
        '5ea1264cc0b5e9e8c4d34b7d',
        '5ea1264cc0b5e9e8c4d34b80',
        '5ea12655c0b5e9e8c4d34bae',
        '5ea1264cc0b5e9e8c4d34b85',
      ],
      corequisites: [],
      type: [1],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34b91',
      code: '146',
      area: 'majorRequirement',
      title: ' ',
      department: 'CS',
      __v: 0,
      credit: '3.0',
    },
    {
      school: 'SJSU',
      prerequisites: [],
      corequisites: [],
      type: [],
      difficulty: 0,
      impaction: 0,
      _id: '5ea12665c0b5e9e8c4d34bb8',
      code: '14A',
      department: 'KIN',
      __v: 0,
    },
    {
      school: 'SJSU',
      prerequisites: ['5ea12655c0b5e9e8c4d34bb0'],
      corequisites: [],
      type: [1],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34b87',
      code: '161A',
      area: 'majorRequirement',
      title: ' ',
      department: 'MATH',
      __v: 0,
      credit: '3.0',
    },
    {
      school: 'SJSU',
      prerequisites: [],
      corequisites: [],
      type: [0],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34b5c',
      code: '15',
      area: 'D3',
      title: ' ',
      department: 'POLS',
      __v: 0,
    },
    {
      school: 'SJSU',
      prerequisites: ['5ea1264cc0b5e9e8c4d34b91'],
      corequisites: [],
      type: [1],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34b96',
      code: '149',
      area: 'majorRequirement',
      title: ' ',
      department: 'CS',
      __v: 0,
      credit: '3.0',
    },
    {
      school: 'SJSU',
      prerequisites: [
        '5ea1264cc0b5e9e8c4d34b91',
        '5ea1264cc0b5e9e8c4d34b80',
        '5ea1264cc0b5e9e8c4d34b85',
        '5ea12655c0b5e9e8c4d34bae',
      ],
      corequisites: [],
      type: [1],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34b99',
      code: '151',
      area: 'majorRequirement',
      title: ' ',
      department: 'CS',
      __v: 0,
      credit: '3.0',
    },
    {
      school: 'SJSU',
      prerequisites: [
        '5ea1264cc0b5e9e8c4d34b91',
        '5ea12656c0b5e9e8c4d34bb4',
        '5ea1264cc0b5e9e8c4d34b89',
        '5ea1264cc0b5e9e8c4d34b88',
      ],
      corequisites: [],
      type: [1],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34b98',
      code: '166',
      area: 'majorRequirement',
      title: ' ',
      department: 'CS',
      __v: 0,
      credit: '3.0',
    },
    {
      school: 'SJSU',
      prerequisites: [],
      corequisites: [],
      type: [],
      difficulty: 0,
      impaction: 0,
      _id: '5ea12665c0b5e9e8c4d34bb9',
      code: '14B',
      department: 'KIN',
      __v: 0,
    },
    {
      school: 'SJSU',
      prerequisites: [],
      corequisites: [],
      type: [0],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264bc0b5e9e8c4d34b08',
      code: '10',
      area: 'C1',
      title: ' ',
      department: 'RTVF',
      __v: 0,
    },
    {
      school: 'SJSU',
      prerequisites: ['5ea1264cc0b5e9e8c4d34b88', '5ea1264cc0b5e9e8c4d34b91'],
      corequisites: [],
      type: [1],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34b8b',
      code: '148',
      area: 'majorRequirement',
      title: ' ',
      department: 'CMPE',
      __v: 0,
      credit: '3.0',
    },
    {
      school: 'SJSU',
      prerequisites: [],
      corequisites: [],
      type: [1],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34b92',
      code: '195E',
      area: 'majorRequirement',
      title: ' ',
      department: 'CMPE',
      __v: 0,
    },
    {
      school: 'SJSU',
      prerequisites: ['5ea1264cc0b5e9e8c4d34b91'],
      corequisites: [],
      type: [1],
      difficulty: 0,
      impaction: 0,
      _id: '5ea1264cc0b5e9e8c4d34b93',
      code: '157A',
      area: 'majorRequirement',
      title: ' ',
      department: 'CS',
      __v: 0,
      credit: '3.0',
    },
    {
      school: 'SJSU',
      prerequisites: [],
      corequisites: [],
      type: [],
      difficulty: 0,
      impaction: 0,
      _id: '5ea12665c0b5e9e8c4d34bba',
      code: '111',
      department: 'RTVF',
      __v: 0,
    },
    {
      school: 'SJSU',
      prerequisites: [],
      corequisites: [],
      type: [],
      difficulty: 0,
      impaction: 0,
      _id: '5ea12665c0b5e9e8c4d34bbb',
      code: '154',
      department: 'CS',
      __v: 0,
    },
  ],
  _id: '5e9d45a99277aad9b3704978',
  email: 'calvin@gmail.com',
  isAdmin: false,
  avatarType: '',
  firstName: '',
  lastName: '',
  school: '',
  bio: '',
  major: 'BS Computer Engineering',
  minor: '',
  catalogYear: null,
  degreePlan: {
    semesters: [
      {
        courses: [
          {
            school: 'SJSU',
            prerequisites: [
              '5ea1264cc0b5e9e8c4d34b85',
              '5ea12656c0b5e9e8c4d34bb1',
            ],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b89',
            code: '102',
            area: 'majorRequirement',
            title: ' ',
            department: 'CMPE',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34bab',
            code: '174',
            area: 'elective',
            title: ' ',
            department: 'CS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [
              '5ea1264bc0b5e9e8c4d34ae7',
              '5ea1264cc0b5e9e8c4d34b7d',
            ],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b80',
            code: '42',
            area: 'majorRequirement',
            title: ' ',
            department: 'MATH',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [],
            difficulty: 0,
            impaction: 0,
            _id: '5ea12665c0b5e9e8c4d34bb5',
            code: '42W',
            department: 'MATH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ab6',
            code: '57',
            area: 'A3',
            title: ' ',
            department: 'PHIL',
            __v: 0,
          },
        ],
        _id: '5ea12665c0b5e9e8c4d34bc0',
        term: 'FALL',
        year: 2017,
        status: 0,
        __v: 0,
      },
      {
        courses: [
          {
            school: 'SJSU',
            prerequisites: [
              '5ea1264cc0b5e9e8c4d34b85',
              '5ea12656c0b5e9e8c4d34bb1',
            ],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b88',
            code: '120',
            area: 'majorRequirement',
            title: ' ',
            department: 'CMPE',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: ['5ea1264cc0b5e9e8c4d34b85'],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b84',
            code: '131',
            area: 'majorRequirement',
            title: ' ',
            department: 'CMPE',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: ['5ea1264ac0b5e9e8c4d34aac'],
            corequisites: [],
            type: [0, 1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b6e',
            code: '10',
            area: 'E1',
            title: ' ',
            department: 'ENGR',
            __v: 1,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [],
            difficulty: 0,
            impaction: 0,
            _id: '5ea12656c0b5e9e8c4d34bb3',
            code: '100W',
            title: ' ',
            department: 'ENGR',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [],
            difficulty: 0,
            impaction: 0,
            _id: '5ea12665c0b5e9e8c4d34bb6',
            code: '15A',
            department: 'HIST',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [],
            difficulty: 0,
            impaction: 0,
            _id: '5ea12665c0b5e9e8c4d34bb7',
            code: '35A',
            department: 'KIN',
            __v: 0,
          },
        ],
        _id: '5ea12665c0b5e9e8c4d34bbf',
        term: 'SPRING',
        year: 2018,
        status: 0,
        __v: 0,
      },
      {
        courses: [
          {
            school: 'SJSU',
            prerequisites: ['5ea1264cc0b5e9e8c4d34b84'],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b86',
            code: '133',
            area: 'majorRequirement',
            title: ' ',
            department: 'CMPE',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: ['5ea1264cc0b5e9e8c4d34b84'],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b8d',
            code: '187',
            area: 'majorRequirement',
            title: ' ',
            department: 'CMPE',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [
              '5ea1264cc0b5e9e8c4d34b7d',
              '5ea1264cc0b5e9e8c4d34b80',
              '5ea12655c0b5e9e8c4d34bae',
              '5ea1264cc0b5e9e8c4d34b85',
            ],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b91',
            code: '146',
            area: 'majorRequirement',
            title: ' ',
            department: 'CS',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [],
            difficulty: 0,
            impaction: 0,
            _id: '5ea12665c0b5e9e8c4d34bb8',
            code: '14A',
            department: 'KIN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: ['5ea12655c0b5e9e8c4d34bb0'],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b87',
            code: '161A',
            area: 'majorRequirement',
            title: ' ',
            department: 'MATH',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b5c',
            code: '15',
            area: 'D3',
            title: ' ',
            department: 'POLS',
            __v: 0,
          },
        ],
        _id: '5ea12665c0b5e9e8c4d34bbe',
        term: 'FALL',
        year: 2018,
        status: 0,
        __v: 0,
      },
      {
        courses: [
          {
            school: 'SJSU',
            prerequisites: ['5ea1264cc0b5e9e8c4d34b91'],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b96',
            code: '149',
            area: 'majorRequirement',
            title: ' ',
            department: 'CS',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [
              '5ea1264cc0b5e9e8c4d34b91',
              '5ea1264cc0b5e9e8c4d34b80',
              '5ea1264cc0b5e9e8c4d34b85',
              '5ea12655c0b5e9e8c4d34bae',
            ],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b99',
            code: '151',
            area: 'majorRequirement',
            title: ' ',
            department: 'CS',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [
              '5ea1264cc0b5e9e8c4d34b91',
              '5ea12656c0b5e9e8c4d34bb4',
              '5ea1264cc0b5e9e8c4d34b89',
              '5ea1264cc0b5e9e8c4d34b88',
            ],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b98',
            code: '166',
            area: 'majorRequirement',
            title: ' ',
            department: 'CS',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [],
            difficulty: 0,
            impaction: 0,
            _id: '5ea12665c0b5e9e8c4d34bb9',
            code: '14B',
            department: 'KIN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b08',
            code: '10',
            area: 'C1',
            title: ' ',
            department: 'RTVF',
            __v: 0,
          },
        ],
        _id: '5ea12665c0b5e9e8c4d34bbd',
        term: 'SPRING',
        year: 2019,
        status: 0,
        __v: 0,
      },
      {
        courses: [
          {
            school: 'SJSU',
            prerequisites: [
              '5ea1264cc0b5e9e8c4d34b88',
              '5ea1264cc0b5e9e8c4d34b91',
            ],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b8b',
            code: '148',
            area: 'majorRequirement',
            title: ' ',
            department: 'CMPE',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b92',
            code: '195E',
            area: 'majorRequirement',
            title: ' ',
            department: 'CMPE',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: ['5ea1264cc0b5e9e8c4d34b91'],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b93',
            code: '157A',
            area: 'majorRequirement',
            title: ' ',
            department: 'CS',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [],
            difficulty: 0,
            impaction: 0,
            _id: '5ea12665c0b5e9e8c4d34bba',
            code: '111',
            department: 'RTVF',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [],
            difficulty: 0,
            impaction: 0,
            _id: '5ea12665c0b5e9e8c4d34bbb',
            code: '154',
            department: 'CS',
            __v: 0,
          },
        ],
        _id: '5ea12665c0b5e9e8c4d34bbc',
        term: 'FALL',
        year: 2019,
        status: 0,
        __v: 0,
      },
    ],
    remainingRequirements: [
      {
        courses: [
          {
            school: 'SJSU',
            prerequisites: ['5ea1264ac0b5e9e8c4d34aac'],
            corequisites: [],
            type: [0, 1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34acc',
            code: '10',
            area: 'B2',
            title: 'The Living World',
            department: 'BIOL',
            __v: 1,
            credit: '3.0',
            description:
              'Provides students with an understanding of the most fundamental concepts of modern biology including ecology (the interaction between organisms and their environment), human inheritance, the structure and function of living organisms, evolution, strategies for survival and reproduction, and biotechnology. GE Area: B2 Notes: Not an elective in the department majors.',
          },
          {
            school: 'SJSU',
            prerequisites: ['5ea1264ac0b5e9e8c4d34aac'],
            corequisites: [],
            type: [0, 1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b12',
            code: '1B',
            area: 'C2',
            title: ' ',
            department: 'ENGL',
            __v: 1,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b7d',
            code: '30',
            area: 'majorRequirement',
            title: ' ',
            department: 'MATH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: ['5ea1264cc0b5e9e8c4d34b7d'],
            corequisites: ['5ea12655c0b5e9e8c4d34bac'],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b7f',
            code: '31',
            area: 'majorRequirement',
            title: ' ',
            department: 'MATH',
            __v: 0,
            credit: '4.0',
          },
          {
            school: 'SJSU',
            prerequisites: ['5ea1264cc0b5e9e8c4d34b7f'],
            corequisites: ['5ea12655c0b5e9e8c4d34bad'],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b7c',
            code: '32',
            area: 'majorRequirement',
            title: ' ',
            department: 'MATH',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [
              '5ea1264ac0b5e9e8c4d34aac',
              '5ea1264cc0b5e9e8c4d34b7d',
            ],
            corequisites: [],
            type: [0, 1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ac7',
            code: '50',
            area: 'B1',
            title: ' ',
            department: 'PHYS',
            __v: 1,
            credit: '4.0',
          },
          {
            school: 'SJSU',
            prerequisites: [
              '5ea1264bc0b5e9e8c4d34ac7',
              '5ea1264cc0b5e9e8c4d34b7f',
            ],
            corequisites: [],
            type: [0, 1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ac8',
            code: '51',
            area: 'B1',
            title: ' ',
            department: 'PHYS',
            __v: 1,
            credit: '4.0',
          },
          {
            school: 'SJSU',
            prerequisites: ['5ea1264cc0b5e9e8c4d34b7f'],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b7e',
            code: '123',
            area: 'majorRequirement',
            title: 'Differential Equations and Linear Algebra',
            department: 'MATH',
            __v: 0,
            credit: '3.0',
            description:
              "Matrices, determinants, systems of linear equations, vector geometry, linear transformations, eigenvalues and eigenvectors, diagonalization, first order differential equations, linear systems of differential equations, higher order differential equations, Laplace transforms. Prerequisite: Math 31 (with a grade of 'C-' or better) or instructor consent.",
          },
          {
            school: 'SJSU',
            prerequisites: [
              '5ea1264cc0b5e9e8c4d34b7f',
              '5ea1264cc0b5e9e8c4d34b80',
            ],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b82',
            code: '142',
            area: 'majorRequirement',
            title: 'Introduction to Combinatorics',
            department: 'MATH',
            __v: 0,
            credit: '3.0',
            description:
              "Sets, permutations, combinations, probability, mathematical induction, counting techniques, generating functions, partitions, recurrence relations, inclusion-exclusion. Polya's theorem and applications to computer science, mathematics, engineering and physical sciences. Prerequisite: MATH 31 and MATH 42 (with a grade of 'C-' or better in each) or instructor consent.",
          },
          {
            school: 'SJSU',
            prerequisites: [
              '5ea1264cc0b5e9e8c4d34b7c',
              '5ea12655c0b5e9e8c4d34baf',
            ],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b81',
            code: '130',
            area: 'majorRequirement',
            title: ' ',
            department: 'ISE',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b83',
            code: '46A',
            area: 'majorRequirement',
            title: ' ',
            department: 'CS',
            __v: 0,
            credit: '4.0',
          },
          {
            school: 'SJSU',
            prerequisites: [
              '5ea1264cc0b5e9e8c4d34b83',
              '5ea1264cc0b5e9e8c4d34b80',
            ],
            corequisites: ['5ea1264cc0b5e9e8c4d34b80'],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b85',
            code: '46B',
            area: 'majorRequirement',
            title: ' ',
            department: 'CS',
            __v: 0,
            credit: '4.0',
          },
          {
            school: 'SJSU',
            prerequisites: ['5ea1264ac0b5e9e8c4d34aac'],
            corequisites: [],
            type: [0, 1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b6e',
            code: '10',
            area: 'E1',
            title: ' ',
            department: 'ENGR',
            __v: 1,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: ['5ea1264cc0b5e9e8c4d34b84'],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b8a',
            code: '165',
            area: 'majorRequirement',
            title: ' ',
            department: 'CMPE',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [
              '5ea1264cc0b5e9e8c4d34b96',
              '5ea12656c0b5e9e8c4d34bb2',
            ],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b8f',
            code: '172',
            area: 'majorRequirement',
            title: ' ',
            department: 'CMPE',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [
              '5ea1264cc0b5e9e8c4d34b86',
              '5ea1264cc0b5e9e8c4d34b81',
              '5ea1264cc0b5e9e8c4d34b87',
              '5ea12656c0b5e9e8c4d34bb3',
            ],
            corequisites: ['5ea1264cc0b5e9e8c4d34b90'],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b8e',
            code: '195A',
            area: 'majorRequirement',
            title: ' ',
            department: 'CMPE',
            __v: 0,
            credit: '2.0',
          },
          {
            school: 'SJSU',
            prerequisites: ['5ea1264cc0b5e9e8c4d34b8e'],
            corequisites: ['5ea1264cc0b5e9e8c4d34b95'],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b8c',
            code: '195B',
            area: 'majorRequirement',
            title: ' ',
            department: 'CMPE',
            __v: 0,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: ['5ea12656c0b5e9e8c4d34bb3'],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b90',
            code: '195A',
            area: 'majorRequirement',
            title: ' ',
            department: 'ENGR',
            __v: 0,
            credit: '1.0',
          },
          {
            school: 'SJSU',
            prerequisites: ['5ea1264cc0b5e9e8c4d34b90'],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b95',
            code: '195B',
            area: 'majorRequirement',
            title: ' ',
            department: 'ENGR',
            __v: 0,
            credit: '1.0',
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b94',
            code: '195F',
            area: 'majorRequirement',
            title: ' ',
            department: 'CMPE',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b97',
            code: '164',
            area: 'majorRequirement',
            title: ' ',
            department: 'ISE',
            __v: 0,
            credit: '3.0',
          },
        ],
        _id: '5ea12b07b4ca1deb95f7665d',
        creditLeft: 57,
        type: 1,
        area: 'majorRequirement',
        user: '5e9d45a99277aad9b3704978',
        __v: 0,
      },
      {
        courses: [
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b9a',
            code: '137',
            area: 'elective',
            title: ' ',
            department: 'CMPE',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b9c',
            code: '139',
            area: 'elective',
            title: ' ',
            department: 'CMPE',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b9b',
            code: '149',
            area: 'elective',
            title: ' ',
            department: 'CMPE',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b9d',
            code: '152',
            area: 'elective',
            title: ' ',
            department: 'CMPE',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b9e',
            code: '181',
            area: 'elective',
            title: ' ',
            department: 'CMPE',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b9f',
            code: '182',
            area: 'elective',
            title: ' ',
            department: 'CMPE',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34ba0',
            code: '188',
            area: 'elective',
            title: ' ',
            department: 'CMPE',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34ba2',
            code: '189',
            area: 'elective',
            title: ' ',
            department: 'CMPE',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34ba1',
            code: '116A',
            area: 'elective',
            title: ' ',
            department: 'CS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34ba3',
            code: '123A',
            area: 'elective',
            title: ' ',
            department: 'CS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34ba5',
            code: '134',
            area: 'elective',
            title: ' ',
            department: 'CS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34ba4',
            code: '152',
            area: 'elective',
            title: ' ',
            department: 'CS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34ba6',
            code: '155',
            area: 'elective',
            title: ' ',
            department: 'CS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34ba7',
            code: '156',
            area: 'elective',
            title: ' ',
            department: 'CS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34ba8',
            code: '157B',
            area: 'elective',
            title: ' ',
            department: 'CS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34baa',
            code: '158B',
            area: 'elective',
            title: ' ',
            department: 'CS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [2],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34ba9',
            code: '159',
            area: 'elective',
            title: ' ',
            department: 'CS',
            __v: 0,
          },
        ],
        _id: '5ea12b07b4ca1deb95f7665e',
        creditLeft: 3,
        type: 2,
        area: 'elective',
        user: '5e9d45a99277aad9b3704978',
        __v: 0,
      },
      {
        courses: [
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264ac0b5e9e8c4d34aa5',
            code: '20',
            area: 'A1',
            title: ' ',
            department: 'COMM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264ac0b5e9e8c4d34aa7',
            code: '20N',
            area: 'A1',
            title: ' ',
            department: 'COMM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264ac0b5e9e8c4d34aa6',
            code: '40',
            area: 'A1',
            title: ' ',
            department: 'COMM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264ac0b5e9e8c4d34aa8',
            code: '2A',
            area: 'A1',
            title: ' ',
            department: 'HUM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264ac0b5e9e8c4d34aa9',
            code: '74',
            area: 'A1',
            title: ' ',
            department: 'CCS',
            __v: 0,
          },
        ],
        _id: '5ea12b07b4ca1deb95f7665f',
        type: 0,
        area: 'A1',
        creditLeft: 3,
        user: '5e9d45a99277aad9b3704978',
        __v: 0,
      },
      {
        courses: [
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264ac0b5e9e8c4d34aac',
            code: '1A',
            area: 'A2',
            title: ' ',
            department: 'ENGL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264ac0b5e9e8c4d34aaa',
            code: '1AS',
            area: 'A2',
            title: ' ',
            department: 'ENGL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264ac0b5e9e8c4d34aab',
            code: '1B',
            area: 'A2',
            title: ' ',
            department: 'HUM',
            __v: 0,
          },
        ],
        _id: '5ea12b07b4ca1deb95f76660',
        type: 0,
        area: 'A2',
        creditLeft: 3,
        user: '5e9d45a99277aad9b3704978',
        __v: 0,
      },
      {
        courses: [
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ab9',
            code: '10',
            area: 'B1',
            title: ' ',
            department: 'ASTR',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ab8',
            code: '1A',
            area: 'B1',
            title: ' ',
            department: 'CHEM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34aba',
            code: '1B',
            area: 'B1',
            title: ' ',
            department: 'CHEM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34abb',
            code: '30A',
            area: 'B1',
            title: ' ',
            department: 'CHEM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34abc',
            code: '5',
            area: 'B1',
            title: ' ',
            department: 'ENGR',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ac0',
            code: '1',
            area: 'B1',
            title: ' ',
            department: 'GEOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34abe',
            code: '3',
            area: 'B1',
            title: ' ',
            department: 'GEOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34abf',
            code: '6',
            area: 'B1',
            title: ' ',
            department: 'GEOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34abd',
            code: '7',
            area: 'B1',
            title: ' ',
            department: 'GEOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ac1',
            code: '9',
            area: 'B1',
            title: ' ',
            department: 'GEOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ac5',
            code: '10',
            area: 'B1',
            title: ' ',
            department: 'METR',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ac2',
            code: '12',
            area: 'B1',
            title: ' ',
            department: 'METR',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ac3',
            code: '1A',
            area: 'B1',
            title: ' ',
            department: 'NUFS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ac4',
            code: '1',
            area: 'B1',
            title: ' ',
            department: 'PHYS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ac6',
            code: '2A',
            area: 'B1',
            title: ' ',
            department: 'PHYS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34aca',
            code: '2B',
            area: 'B1',
            title: ' ',
            department: 'PHYS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ac9',
            code: '23',
            area: 'B1',
            title: ' ',
            department: 'PHYS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [
              '5ea1264ac0b5e9e8c4d34aac',
              '5ea1264cc0b5e9e8c4d34b7d',
            ],
            corequisites: [],
            type: [0, 1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ac7',
            code: '50',
            area: 'B1',
            title: ' ',
            department: 'PHYS',
            __v: 1,
            credit: '4.0',
          },
          {
            school: 'SJSU',
            prerequisites: [
              '5ea1264bc0b5e9e8c4d34ac7',
              '5ea1264cc0b5e9e8c4d34b7f',
            ],
            corequisites: [],
            type: [0, 1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ac8',
            code: '51',
            area: 'B1',
            title: ' ',
            department: 'PHYS',
            __v: 1,
            credit: '4.0',
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34acb',
            code: '52',
            area: 'B1',
            title: ' ',
            department: 'PHYS',
            __v: 0,
          },
        ],
        _id: '5ea12b07b4ca1deb95f76661',
        type: 0,
        area: 'B1',
        creditLeft: 3,
        user: '5e9d45a99277aad9b3704978',
        __v: 0,
      },
      {
        courses: [
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ada',
            code: '102',
            area: 'B3',
            title: ' ',
            department: 'ASTR',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34adc',
            code: '65L',
            area: 'B3',
            title: ' ',
            department: 'BIOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34adb',
            code: '150',
            area: 'B3',
            title: ' ',
            department: 'BIOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34add',
            code: '150',
            area: 'B3',
            title: ' ',
            department: 'GEOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34adf',
            code: '4L',
            area: 'B3',
            title: ' ',
            department: 'GEOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ade',
            code: '1L',
            area: 'B3',
            title: ' ',
            department: 'PHYS',
            __v: 0,
          },
        ],
        _id: '5ea12b07b4ca1deb95f76663',
        type: 0,
        area: 'B3',
        creditLeft: 0,
        user: '5e9d45a99277aad9b3704978',
        __v: 0,
      },
      {
        courses: [
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ae2',
            code: '67',
            area: 'B4',
            title: ' ',
            department: 'HS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ae1',
            code: '15',
            area: 'B4',
            title: ' ',
            department: 'JS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ae0',
            code: '1',
            area: 'B4',
            title: ' ',
            department: 'MATH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ae3',
            code: '10',
            area: 'B4',
            title: ' ',
            department: 'MATH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ae4',
            code: '10A',
            area: 'B4',
            title: ' ',
            department: 'MATH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ae8',
            code: '10P',
            area: 'B4',
            title: ' ',
            department: 'MATH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ae6',
            code: '12',
            area: 'B4',
            title: ' ',
            department: 'MATH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ae5',
            code: '18A',
            area: 'B4',
            title: ' ',
            department: 'MATH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ae7',
            code: '19',
            area: 'B4',
            title: ' ',
            department: 'MATH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ae9',
            code: '30*',
            area: 'B4',
            title: ' ',
            department: 'MATH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34aed',
            code: '30P*',
            area: 'B4',
            title: ' ',
            department: 'MATH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34aeb',
            code: '30PL*',
            area: 'B4',
            title: ' ',
            department: 'MATH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34aea',
            code: '31*',
            area: 'B4',
            title: ' ',
            department: 'MATH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34aec',
            code: '32*',
            area: 'B4',
            title: ' ',
            department: 'MATH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34aee',
            code: '70*',
            area: 'B4',
            title: ' ',
            department: 'MATH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34af2',
            code: '71*',
            area: 'B4',
            title: ' ',
            department: 'MATH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34af0',
            code: '9',
            area: 'B4',
            title: ' ',
            department: 'PHIL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34aef',
            code: '15',
            area: 'B4',
            title: ' ',
            department: 'SOCI',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34af1',
            code: '15',
            area: 'B4',
            title: ' ',
            department: 'SOCS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34af3',
            code: '95',
            area: 'B4',
            title: ' ',
            department: 'STAT',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34af4',
            code: '15F-015S',
            area: 'B4',
            title: ' ',
            department: 'UNVS/MATH',
            __v: 0,
          },
        ],
        _id: '5ea12b07b4ca1deb95f76664',
        type: 0,
        area: 'B4',
        creditLeft: 3,
        user: '5e9d45a99277aad9b3704978',
        __v: 0,
      },
      {
        courses: [
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34acd',
            code: '12',
            area: 'B2',
            title: ' ',
            department: 'ANTH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: ['5ea1264ac0b5e9e8c4d34aac'],
            corequisites: [],
            type: [0, 1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34acc',
            code: '10',
            area: 'B2',
            title: 'The Living World',
            department: 'BIOL',
            __v: 1,
            credit: '3.0',
            description:
              'Provides students with an understanding of the most fundamental concepts of modern biology including ecology (the interaction between organisms and their environment), human inheritance, the structure and function of living organisms, evolution, strategies for survival and reproduction, and biotechnology. GE Area: B2 Notes: Not an elective in the department majors.',
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ace',
            code: '20',
            area: 'B2',
            title: ' ',
            department: 'BIOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34acf',
            code: '21',
            area: 'B2',
            title: ' ',
            department: 'BIOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ad4',
            code: '30',
            area: 'B2',
            title: ' ',
            department: 'BIOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ad0',
            code: '31',
            area: 'B2',
            title: ' ',
            department: 'BIOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ad2',
            code: '65',
            area: 'B2',
            title: ' ',
            department: 'BIOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ad3',
            code: '65O',
            area: 'B2',
            title: ' ',
            department: 'BIOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ad1',
            code: '66',
            area: 'B2',
            title: ' ',
            department: 'BIOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ad9',
            code: '10',
            area: 'B2',
            title: ' ',
            department: 'ENVS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ad5',
            code: '8',
            area: 'B2',
            title: ' ',
            department: 'GEOL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ad6',
            code: '1B',
            area: 'B2',
            title: ' ',
            department: 'GLST',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ad8',
            code: '20',
            area: 'B2',
            title: ' ',
            department: 'MICR',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ad7',
            code: '16',
            area: 'B2',
            title: ' ',
            department: 'NUFS',
            __v: 0,
          },
        ],
        _id: '5ea12b07b4ca1deb95f76662',
        type: 0,
        area: 'B2',
        creditLeft: 3,
        user: '5e9d45a99277aad9b3704978',
        __v: 0,
      },
      {
        courses: [
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b0c',
            code: '1B',
            area: 'C2',
            title: ' ',
            department: 'AMS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b0e',
            code: '1A',
            area: 'C2',
            title: ' ',
            department: 'CHIN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b0b',
            code: '1B',
            area: 'C2',
            title: ' ',
            department: 'CHIN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b0d',
            code: '25A',
            area: 'C2',
            title: ' ',
            department: 'CHIN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b0f',
            code: '25B',
            area: 'C2',
            title: ' ',
            department: 'CHIN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: ['5ea1264ac0b5e9e8c4d34aac'],
            corequisites: [],
            type: [0, 1],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b12',
            code: '1B',
            area: 'C2',
            title: ' ',
            department: 'ENGL',
            __v: 1,
            credit: '3.0',
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b11',
            code: '10',
            area: 'C2',
            title: ' ',
            department: 'ENGL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b13',
            code: '20',
            area: 'C2',
            title: ' ',
            department: 'ENGL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b10',
            code: '21',
            area: 'C2',
            title: ' ',
            department: 'ENGL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b14',
            code: '22',
            area: 'C2',
            title: ' ',
            department: 'ENGL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b17',
            code: '30',
            area: 'C2',
            title: ' ',
            department: 'ENGL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b16',
            code: '40',
            area: 'C2',
            title: ' ',
            department: 'ENGL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b18',
            code: '71',
            area: 'C2',
            title: ' ',
            department: 'ENGL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b15',
            code: '78',
            area: 'C2',
            title: ' ',
            department: 'ENGL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34afe',
            code: '25',
            area: 'C1',
            title: ' ',
            department: 'FORL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b1b',
            code: '1A',
            area: 'C2',
            title: ' ',
            department: 'FREN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b1a',
            code: '1B',
            area: 'C2',
            title: ' ',
            department: 'FREN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b1c',
            code: '25A',
            area: 'C2',
            title: ' ',
            department: 'FREN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b19',
            code: '25B',
            area: 'C2',
            title: ' ',
            department: 'FREN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b1d',
            code: '1A',
            area: 'C2',
            title: ' ',
            department: 'GERM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b1f',
            code: '1B',
            area: 'C2',
            title: ' ',
            department: 'GERM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b1e',
            code: '25A',
            area: 'C2',
            title: ' ',
            department: 'GERM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b20',
            code: '25B',
            area: 'C2',
            title: ' ',
            department: 'GERM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34aff',
            code: '1A',
            area: 'C1',
            title: ' ',
            department: 'HUM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ab5',
            code: '2B',
            area: 'A3',
            title: ' ',
            department: 'HUM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b23',
            code: '10',
            area: 'C2',
            title: ' ',
            department: 'HUM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b22',
            code: '1A',
            area: 'C2',
            title: ' ',
            department: 'JPN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b25',
            code: '1B',
            area: 'C2',
            title: ' ',
            department: 'JPN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b21',
            code: '25A',
            area: 'C2',
            title: ' ',
            department: 'JPN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b26',
            code: '25B',
            area: 'C2',
            title: ' ',
            department: 'JPN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b27',
            code: '12',
            area: 'C2',
            title: ' ',
            department: 'MUSC',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b28',
            code: '10',
            area: 'C2',
            title: ' ',
            department: 'PHIL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b2e',
            code: '61',
            area: 'C2',
            title: ' ',
            department: 'PHIL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b24',
            code: '70A',
            area: 'C2',
            title: ' ',
            department: 'PHIL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b30',
            code: '70B',
            area: 'C2',
            title: ' ',
            department: 'PHIL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b2a',
            code: '3',
            area: 'C2',
            title: ' ',
            department: 'POLS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b2b',
            code: '1A',
            area: 'C2',
            title: ' ',
            department: 'PORT',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b2f',
            code: '1B',
            area: 'C2',
            title: ' ',
            department: 'PORT',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b29',
            code: '70',
            area: 'C2',
            title: ' ',
            department: 'RELS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b33',
            code: '90',
            area: 'C2',
            title: ' ',
            department: 'RELS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b31',
            code: '90',
            area: 'C2',
            title: ' ',
            department: 'HUM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b2c',
            code: '90',
            area: 'C2',
            title: ' ',
            department: 'JWSS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b32',
            code: '90',
            area: 'C2',
            title: ' ',
            department: 'MDES',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b2d',
            code: '1A',
            area: 'C2',
            title: ' ',
            department: 'SPAN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b37',
            code: '1B',
            area: 'C2',
            title: ' ',
            department: 'SPAN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b34',
            code: '25A',
            area: 'C2',
            title: ' ',
            department: 'SPAN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b36',
            code: '25B',
            area: 'C2',
            title: ' ',
            department: 'SPAN',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34b35',
            code: '13',
            area: 'C2',
            title: ' ',
            department: 'TA',
            __v: 0,
          },
        ],
        _id: '5ea12b07b4ca1deb95f76665',
        type: 0,
        area: 'C2',
        creditLeft: 3,
        user: '5e9d45a99277aad9b3704978',
        __v: 0,
      },
      {
        courses: [
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b38',
            code: '11',
            area: 'D1',
            title: ' ',
            department: 'ANTH',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b3a',
            code: '30',
            area: 'D1',
            title: ' ',
            department: 'CCS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b39',
            code: '75',
            area: 'D1',
            title: ' ',
            department: 'CHAD',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b3b',
            code: '25',
            area: 'D1',
            title: ' ',
            department: 'ENGR',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b3c',
            code: '25',
            area: 'D1',
            title: ' ',
            department: 'CS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b3d',
            code: '10',
            area: 'D1',
            title: ' ',
            department: 'COMM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b40',
            code: '21',
            area: 'D1',
            title: ' ',
            department: 'COMM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b3f',
            code: '1B',
            area: 'D1',
            title: ' ',
            department: 'ECON',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b3e',
            code: '1',
            area: 'D1',
            title: ' ',
            department: 'ENVS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b41',
            code: '10',
            area: 'D1',
            title: ' ',
            department: 'GEOG',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b47',
            code: '15',
            area: 'D1',
            title: ' ',
            department: 'HS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b45',
            code: '15',
            area: 'D1',
            title: ' ',
            department: 'GERO',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b44',
            code: '15',
            area: 'D1',
            title: ' ',
            department: 'RECL',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b43',
            code: '50',
            area: 'D1',
            title: ' ',
            department: 'JOUR',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b42',
            code: '20',
            area: 'D1',
            title: ' ',
            department: 'LING',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34ab3',
            code: '24',
            area: 'A3',
            title: ' ',
            department: 'LING',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b46',
            code: '25',
            area: 'D1',
            title: ' ',
            department: 'LING',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b4a',
            code: '1',
            area: 'D1',
            title: ' ',
            department: 'PSYC',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b49',
            code: '1',
            area: 'D1',
            title: ' ',
            department: 'SOCI',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b48',
            code: '5Q',
            area: 'D1',
            title: ' ',
            department: 'WOMS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b4b',
            code: '10',
            area: 'D1',
            title: ' ',
            department: 'WOMS',
            __v: 0,
          },
        ],
        _id: '5ea12b07b4ca1deb95f76666',
        type: 0,
        area: 'D1',
        creditLeft: 3,
        user: '5e9d45a99277aad9b3704978',
        __v: 0,
      },
      {
        courses: [
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b4d',
            code: '25',
            area: 'D2',
            title: ' ',
            department: 'AAS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b4e',
            code: '25',
            area: 'D2',
            title: ' ',
            department: 'AFAM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b4f',
            code: '25',
            area: 'D2',
            title: ' ',
            department: 'CCS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b4c',
            code: '33A',
            area: 'D2',
            title: ' ',
            department: 'AAS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b50',
            code: '2A',
            area: 'D2',
            title: ' ',
            department: 'AFAM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264bc0b5e9e8c4d34af7',
            code: '1A',
            area: 'C1',
            title: ' ',
            department: 'AMS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b52',
            code: '10A',
            area: 'D2',
            title: ' ',
            department: 'CCS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b51',
            code: '12',
            area: 'D2',
            title: ' ',
            department: 'GEOG',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b53',
            code: '10A',
            area: 'D2',
            title: ' ',
            department: 'HIST',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b56',
            code: '10B',
            area: 'D2',
            title: ' ',
            department: 'HIST',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b55',
            code: '15',
            area: 'D2',
            title: ' ',
            department: 'HIST',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264ac0b5e9e8c4d34aa8',
            code: '2A',
            area: 'A1',
            title: ' ',
            department: 'HUM',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b57',
            code: '2',
            area: 'D2',
            title: ' ',
            department: 'POLS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b54',
            code: '20',
            area: 'D2',
            title: ' ',
            department: 'WOMS',
            __v: 0,
          },
          {
            school: 'SJSU',
            prerequisites: [],
            corequisites: [],
            type: [0],
            difficulty: 0,
            impaction: 0,
            _id: '5ea1264cc0b5e9e8c4d34b58',
            code: '20',
            area: 'D2',
            title: ' ',
            department: 'AAS',
            __v: 0,
          },
        ],
        _id: '5ea12b07b4ca1deb95f76667',
        type: 0,
        area: 'D2',
        creditLeft: 3,
        user: '5e9d45a99277aad9b3704978',
        __v: 0,
      },
    ],
    _id: '5ea12b07b4ca1deb95f76668',
    user: '5e9d45a99277aad9b3704978',
    __v: 0,
  },
};

export default response;
