const response = {
  semesterList: [
    {
      term: 'FALL',
      year: 2017,
      courses: [
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [0, 1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4d3b385e39b8ffe90d',
          code: '10',
          area: 'B2',
          title: ' ',
          department: 'BIOL',
          __v: 2,
          credit: ' ',
          description:
            'Provides students with an understanding of the most fundamental concepts of modern biology including ecology (the interaction between organisms and their environment), human inheritance, the structure and function of living organisms, evolution, strategies for survival and reproduction, and biotechnology. GE Area: B2 Notes: Not an elective in the department majors.',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe9c7',
          code: '102',
          area: 'majorRequirement',
          title: ' ',
          department: 'CMPE',
          __v: 1,
          credit: ' ',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [2],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe9e8',
          code: '174',
          area: 'elective',
          title: ' ',
          department: 'CS',
          __v: 0,
          credit: ' ',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe9c0',
          code: '42',
          area: 'majorRequirement',
          title: ' ',
          department: 'MATH',
          __v: 1,
          credit: ' ',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a573b385e39b8ffe9f4',
          code: '42W',
          department: 'MATH',
          __v: 0,
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [0],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4d3b385e39b8ffe8f8',
          code: '57',
          area: 'A3',
          title: ' ',
          department: 'PHIL',
          __v: 0,
          credit: ' ',
        },
      ],
      status: 0,
    },
    {
      term: 'SPRING',
      year: 2018,
      courses: [
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe9ca',
          code: '120',
          area: 'majorRequirement',
          title: ' ',
          department: 'CMPE',
          __v: 1,
          credit: ' ',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe9c8',
          code: '131',
          area: 'majorRequirement',
          title: ' ',
          department: 'CMPE',
          __v: 1,
          credit: ' ',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [0, 1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe9af',
          code: '10',
          area: 'E1',
          title: ' ',
          department: 'ENGR',
          __v: 2,
          credit: ' ',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a513b385e39b8ffe9f2',
          code: '100W',
          title: ' ',
          department: 'ENGR',
          __v: 0,
          credit: ' ',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a573b385e39b8ffe9f5',
          code: '15A',
          department: 'HIST',
          __v: 0,
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a573b385e39b8ffe9f6',
          code: '35A',
          department: 'KIN',
          __v: 0,
        },
      ],
      status: 0,
    },
    {
      term: 'FALL',
      year: 2018,
      courses: [
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe9c9',
          code: '133',
          area: 'majorRequirement',
          title: ' ',
          department: 'CMPE',
          __v: 1,
          credit: ' ',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe9cd',
          code: '187',
          area: 'majorRequirement',
          title: ' ',
          department: 'CMPE',
          __v: 1,
          credit: ' ',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe9d5',
          code: '146',
          area: 'majorRequirement',
          title: ' ',
          department: 'CS',
          __v: 1,
          credit: ' ',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a573b385e39b8ffe9f7',
          code: '14A',
          department: 'KIN',
          __v: 0,
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe9c6',
          code: '161A',
          area: 'majorRequirement',
          title: ' ',
          department: 'MATH',
          __v: 1,
          credit: ' ',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [0],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe9a1',
          code: '15',
          area: 'D3',
          title: ' ',
          department: 'POLS',
          __v: 0,
          credit: ' ',
        },
      ],
      status: 0,
    },
    {
      term: 'SPRING',
      year: 2019,
      courses: [
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe9d4',
          code: '149',
          area: 'majorRequirement',
          title: ' ',
          department: 'CS',
          __v: 1,
          credit: ' ',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe9d3',
          code: '151',
          area: 'majorRequirement',
          title: ' ',
          department: 'CS',
          __v: 1,
          credit: ' ',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe9d8',
          code: '166',
          area: 'majorRequirement',
          title: ' ',
          department: 'CS',
          __v: 1,
          credit: ' ',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a573b385e39b8ffe9f8',
          code: '14B',
          department: 'KIN',
          __v: 0,
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [0],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe94a',
          code: '10',
          area: 'C1',
          title: ' ',
          department: 'RTVF',
          __v: 0,
          credit: ' ',
        },
      ],
      status: 0,
    },
    {
      term: 'FALL',
      year: 2019,
      courses: [
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe9cc',
          code: '148',
          area: 'majorRequirement',
          title: ' ',
          department: 'CMPE',
          __v: 1,
          credit: ' ',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a573b385e39b8ffe9f9',
          code: '195E',
          department: 'CMPE',
          __v: 0,
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [1],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a4e3b385e39b8ffe9d2',
          code: '157A',
          area: 'majorRequirement',
          title: ' ',
          department: 'CS',
          __v: 1,
          credit: ' ',
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a573b385e39b8ffe9fa',
          code: '111',
          department: 'RTVF',
          __v: 0,
        },
        {
          school: 'SJSU',
          prerequisites: [],
          corequisites: [],
          type: [],
          difficulty: 0,
          impaction: 0,
          _id: '5e9e3a573b385e39b8ffe9fb',
          code: '154',
          department: 'CS',
          __v: 0,
        },
      ],
      status: 0,
    },
    {
      term: 'SPRING',
      year: 2020,
      courses: [],
      status: 1,
    },
  ],
  otherInfo: [
    '[WST]: Qualify for taking upper courses such as 100W Course',
    'AP English Literature & Compostn',
    'AP Environmental Science',
    'AP U . S . Government & Politics',
  ],
  major: 'BS Computer Engineering',
};

export default response;
