// User Constants
export const USER_NAME_IS_EMPTY = 'USER_NAME_IS_EMPTY';
export const EMAIL_IS_EMPTY = 'EMAIL_IS_EMPTY';
export const ROLE_IS_EMPTY = 'ROLE_IS_EMPTY';
export const PASSWORD_IS_EMPTY = 'PASSWORD_IS_EMPTY';
export const PASSWORD_LENGTH_MUST_BE_MORE_THAN_8 =
  'PASSWORD_LENGTH_MUST_BE_MORE_THAN_8';
export const WRONG_PASSWORD = 'WRONG_PASSWORD';
export const USER_EXISTS_ALREADY = 'USER_EXISTS_ALREADY';
export const USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST';
export const TOKEN_IS_EMPTY = 'TOKEN_IS_EMPTY';
export const EMAIL_IS_IN_WRONG_FORMAT = 'EMAIL_IS_IN_WRONG_FORMAT';
export const NAME_IS_INVALID = 'FIRST_NAME_IS_INVALID';

// Course Constants
export const COURSE_SCHOOL_IS_EMPTY = 'COURSE_SCHOOL_IS_EMPTY';
export const COURSE_EXISTS_ALREADY = 'COURSE_EXISTS_ALREADY';
export const COURSE_DOES_NOT_EXIST = 'COURSE_DOES_NOT_EXIST';
export const SCHOOL_DOES_NOT_EXIST = 'SCHOOL_DOES_NOT_EXIST';
export const COURSE_CODE_IS_EMPTY = 'COURSE_CODE_IS_EMPTY';
export const COURSE_TITLE_IS_EMPTY = 'COURSE_TITLE_IS_EMPTY';
export const COURSE_DESCRIPTION_IS_EMPTY = 'COURSE_DESCRIPTION_IS_EMPTY';
export const COURSE_TERMS_OFFERED_IS_EMPTY = 'COURSE_TERMS_OFFERED_IS_EMPTY';
export const COURSE_ID_IS_EMPTY = 'COURSE_ID_IS_EMPTY';
export const FAILED_TO_CREATE_COURSE = 'FAILED_TO_CREATE_COURSE';
export const COURSE_DEPARTMENT_IS_EMPTY = 'COURSE_DEPARTMENT_IS_EMPTY';

// Semester Constants
export const SEMESTER_EXISTS_ALREADY = 'SEMESTER_EXISTS_ALREADY';
export const SEMESTER_TERM_IS_EMPTY = 'SEMESTER_TERM_IS_EMPTY';
export const SEMESTER_YEAR_IS_EMPTY = 'SEMESTER_YEAR_IS_EMPTY';
export const SEMESTER_COURSES_ARE_EMPTY = 'SEMESTER_COURSES_ARE_EMPTY';
export const SEMESTER_ID_IS_EMPTY = 'SEMESTER_ID_IS_EMPTY';
export const SEMESTER_NOT_FOUND = 'SEMESTER_NOT_FOUND';
export const YEAR_CONTAINS_FORBIDDEN_CHARACTERS =
  'YEAR_CONTAINS_FORBIDDEN_CHARACTERS';

// for both course and semester
export const DOES_NOT_CONTAIN_A_DIGIT = 'DOES_NOT_CONTAIN_A_DIGIT';
export const NO_DATA_TO_UPDATE = 'NO_DATA_TO_UPDATE';
export const ID_IS_INVALID = 'ID_IS_INVALID';

/* Degree Program Constants */
export const SCHOOL_FIELD_IS_REQUIRED = 'SCHOOL_FIELD_IS_REQUIRED';
export const SCHOOL_FIELD_IS_EMPTY = 'SCHOOL_FIELD_IS_EMPTY';
export const SCHOOL_FIELD_CONTAINS_FORBIDDEN_CHARACTERS =
  'SCHOOL_FIELD_CONTAINS_FORBIDDEN_CHARACTERS';
export const MAJOR_FIELD_IS_REQUIRED = 'MAJOR_FIELD_IS_REQUIRED';
export const MAJOR_FIELD_IS_EMPTY = 'MAJOR_FIELD_IS_EMPTY';
export const MAJOR_FIELD_CONTAINS_FORBIDDEN_CHARACTERS =
  'MAJOR_FIELD_CONTAINS_FORBIDDEN_CHARACTERS';
export const CATALOGYEAR_IS_REQUIRED = 'CATALOGYEAR_IS_REQUIRED';
export const CATALOGYEAR_IS_EMPTY = 'CATALOGYEAR_IS_EMPTY';
export const CATALOGYEAR_CONTAINS_FORBIDDEN_CHARACTERS =
  'CATALOGYEAR_CONTAINS_FORBIDDEN_CHARACTERS';
export const REQUIREMENTOBJECT_IS_REQUIRED = 'REQUIREMENTOBJECT_IS_REQUIRED';
export const REQUIREMENTOBJECT_NOT_AN_OBJECT =
  'REQUIREMENTOBJECT_NOT_AN_OBJECT';
export const REQUIREMENTOBJECT_IS_EMPTY = 'REQUIREMENTOBJECT_IS_EMPTY';
export const REQUIREMENTOBJECT_INCORRECT_STRUCTURE =
  'REQUIREMENTOBJECT_INCORRECT_STRUCTURE';
export const ID_IS_REQUIRED = 'ID_IS_REQUIRED';
export const ID_OR_ALL_THREE_OTHER_PARAMETERS_IS_REQUIRED =
  'ID_OR_ALL_THREE_OTHER_PARAMETERS_IS_REQUIRED';
export const ID_OR_ANY_OF_THREE_PARAMETERS_IS_REQUIRED =
  'ID_OR_ANY_OF_THREE_PARAMETERS_IS_REQUIRED';
export const DEGREE_PROGRAM_ALREADY_EXISTS = 'DEGREE_PROGRAM_ALREADY_EXISTS';
export const DEGREE_PROGRAM_NOT_FOUND = 'DEGREE_PROGRAM_NOT_FOUND';
export const FAILED_TO_CREATE_PROGRAM = 'FAILED_TO_CREATE_PROGRAM';

/* Profile Constants */
export const USER_ID_IS_REQUIRED = 'USER_ID_IS_REQUIRED';
export const USER_ID_IS_EMPTY = 'USER_ID_IS_EMPTY';
export const USER_ID_IS_INVALID = 'USER_ID_IS_INVALID';
export const AVATAR_URL_IS_EMPTY = 'AVATAR_URL_IS_EMPTY';
export const AVATAR_URL_IS_INVALID = 'AVATAR_URL_IS_INVALID';
export const AVATAR_TYPE_IS_EMPTY = 'AVATAR_TYPE_IS_EMPTY';
export const AVATAR_TYPE_IS_INVALID = 'AVATAR_TYPE_IS_INVALID';
export const FIRST_NAME_IS_EMPTY = 'FIRST_NAME_IS_EMPTY';
export const FIRST_NAME_IS_INVALID = 'FIRST_NAME_IS_INVALID';
export const LAST_NAME_IS_EMPTY = 'LAST_NAME_IS_EMPTY';
export const LAST_NAME_IS_INVALID = 'LAST_NAME_IS_INVALID';
export const BIO_IS_EMPTY = 'BIO_IS_EMPTY';
export const BIO_IS_TOO_LONG = 'BIO_IS_TOO_LONG';
export const MAJOR_IS_EMPTY = 'MAJOR_IS_EMPTY';
export const MAJOR_IS_INVALID = 'MAJOR_IS_INVALID';
export const MINOR_IS_EMPTY = 'MINOR_IS_EMPTY';
export const MINOR_IS_INVALID = 'MINOR_IS_INVALID';
export const CATALOG_YEAR_IS_EMPTY = 'CATALOG_YEAR_IS_EMPTY';
export const CATALOG_YEAR_IS_INVALID = 'CATALOG_YEAR_IS_INVALID';
export const DEGREE_PLAN_ID_IS_EMPTY = 'DEGREE_PLAN_ID_IS_EMPTY';
export const INVALID_GRAD_DATE = 'INVALID_GRAD_DATE';
export const UNAUTHORIZED_CHARACTER = 'UNAUTHORIZED_CHARACTER';
export const INVALID_ID = 'INVALID_ID';
export const PARAMETERS_REQUIRED = 'PARAMETERS_REQUIRED';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const BOOLEAN_VALUES_ONLY = 'BOOLEAN_VALUES_ONLY';

/* Degree Plan Constants */
export const PLAN_ID_IS_EMPTY = 'PLAN_ID_IS_EMPTY';
export const COURSE_NAMES_ONLY_MUST_BE_BOOLEAN =
  'COURSE_NAMES_ONLY_MUST_BE_BOOLEAN';
export const COURSE_NAMES_ONLY_FIELD_IS_EMPTY =
  'COURSE_NAMES_ONLY_FIELD_IS_EMPTY';
export const PARAMETERS_IS_EMPTY = 'PARAMETERS_IS_EMPTY';
export const PARAMETERS_NOT_RECOGNIZED = 'PARAMETERS_NOT_RECOGNIZED';
export const INVALID_PARAMETERS = 'INVALID_PARAMETERS';
export const USER_OR_PLAN_ID_REQUIRED = 'USER_OR_PLAN_ID_REQUIRED';
export const PLAN_NOT_FOUND = 'PLAN_NOT_FOUND';
export const SEMESTERS_FIELD_IS_REQUIRED = 'SEMESTERS_FIELD_IS_REQUIRED';
export const SEMESTERS_IS_INVALID = 'SEMESTERS_IS_INVALID';
export const PLAN_ID_FIELD_IS_REQUIRED = 'PLAN_ID_FIELD_IS_REQUIRED';
export const USER_ALREADY_HAS_PLAN = 'USER_ALREADY_HAS_PLAN';
export const FAILED_TO_CREATE_PLAN = 'FAILED_TO_CREATE_PLAN';
export const FAILED_TO_UPDATE_USER = 'FAILED_TO_UPDATE_USER';
export const USER_DOES_NOT_HAVE_DEGREE_PLAN = 'USER_DOES_NOT_HAVE_DEGREE_PLAN';

// Severe server error. Check the server console.
export const SERVER_ERROR = 'SERVER_ERROR';
export const SOME_THING_WENT_WRONG = 'SOME_THING_WENT_WRONG';
export const KEY_IS_INVALID = 'KEY_IS_INVALID';

// Requirement
export const REQUIREMENT_EXISTS_ALREADY = 'REQUIREMENT_EXISTS_ALREADY';
export const REQUIREMENT_TYPE_IS_INVALID = 'REQUIREMENT_TYPE_IS_INVALID';
export const REQUIREMENT_AREA_IS_INVALID = 'REQUIREMENT_AREA_IS_INVALID';
export const REQUIREMENT_NAME_IS_INVALID = 'REQUIREMENT_NAME_IS_INVALID';
export const REQUIREMENT_SCHOOL_IS_INVALID = 'REQUIREMENT_SCHOOL_IS_INVALID';
export const REQUIREMENT_MAJOR_IS_INVALID = 'REQUIREMENT_MAJOR_IS_INVALID';
export const REQUIREMENT_REQUIRED_CREDIT_IS_INVALID =
  'REQUIREMENT_REQUIRED_CREDIT_IS_INVALID';
export const REQUIREMENT_COURSES_IS_INVALID = 'REQUIREMENT_COURSES_IS_INVALID';
export const FAILED_TO_UPDATE_REQUIREMENT = 'FAILED_TO_UPDATE_REQUIREMENT';
export const FAILED_TO_DELETE_REQUIREMENT = 'FAILED_TO_DELETE_REQUIREMENT';
export const REQUIREMENT_DOES_NOT_EXIST = 'REQUIREMENT_DOES_NOT_EXIST';
