export const SOME_THING_WENT_WRONG = 'SOME_THING_WENT_WRONG';

// for users
export const USER_NAME_IS_EMPTY = 'USER_NAME_IS_EMPTY';
export const EMAIL_IS_EMPTY = 'EMAIL_IS_EMPTY';
export const ROLE_IS_EMPTY = 'ROLE_IS_EMPTY';
export const PASSWORD_IS_EMPTY = 'PASSWORD_IS_EMPTY';
export const PASSWORD_LENGTH_MUST_BE_MORE_THAN_8 =
  'PASSWORD_LENGTH_MUST_BE_MORE_THAN_8';
export const WRONG_PASSWORD = 'WRONG_PASSWORD';
export const USER_EXISTS_ALREADY = 'USER_EXISTS_ALREADY';
export const USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST';
export const TOKEN_IS_EMPTY = 'TOKEN_IS_EMPTY';
export const EMAIL_IS_IN_WRONG_FORMAT = 'EMAIL_IS_IN_WRONG_FORMAT';
export const NAME_IS_INVALID = 'FIRST_NAME_IS_INVALID';

// for courses
export const COURSE_SCHOOL_IS_EMPTY = 'COURSE_SCHOOL_IS_EMPTY';
export const COURSE_EXISTS_ALREADY = 'COURSE_EXISTS_ALREADY';
export const COURSE_DOES_NOT_EXIST = 'COURSE_DOES_NOT_EXIST';
export const SCHOOl_DOES_NOT_EXIST = 'SCHOOl_DOES_NOT_EXIST';
export const COURSE_CODE_IS_EMPTY = 'COURSE_CODE_IS_EMPTY';
export const COURSE_TITLE_IS_EMPTY = 'COURSE_TITLE_IS_EMPTY';
export const COURSE_DESCRIPTION_IS_EMPTY = 'COURSE_DESCRIPTION_IS_EMPTY';
export const COURSE_TERMS_OFFERED_IS_EMPTY = 'COURSE_TERMS_OFFERED_IS_EMPTY';
export const COURSE_ID_IS_EMPTY = 'COURSE_ID_IS_EMPTY';

// for semester
export const SEMESTER_EXISTS_ALREADY = 'SEMESTER_EXISTS_ALREADY';
export const SEMESTER_TERM_IS_EMPTY = 'SEMESTER_TERM_IS_EMPTY';
export const SEMESTER_YEAR_IS_EMPTY = 'SEMESTER_YEAR_IS_EMPTY';
export const SEMESTER_COURSES_ARE_EMPTY = 'SEMESTER_COURSES_ARE_EMPTY';
export const SEMESTER_ID_IS_EMPTY = 'SEMESTER_ID_IS_EMPTY';
export const SEMESTER_NOT_FOUND = 'SEMESTER_NOT_FOUND';
export const YEAR_CONTAINS_FORBIDDEN_CHARACTERS =
  'YEAR_CONTAINS_FORBIDDEN_CHARACTERS';

// for both course and semester
export const DOES_NOT_CONTAIN_A_DIGIT = 'DOES_NOT_CONTAIN_A_DIGIT';
export const NO_DATA_TO_UPDATE = 'NO_DATA_TO_UPDATE';
export const ID_IS_INVALID = 'ID_IS_INVALID';
